/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userproject;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Dheeraj Yadav
 */
public class confolist extends javax.swing.JFrame {

    /**
     * Creates new form confolist
     */
    public confolist() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lbloco = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtopincode = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        op = new javax.swing.JRadioButton();
        cod = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        tbnpay = new javax.swing.JButton();
        txtoname = new javax.swing.JTextField();
        txtomobile = new javax.swing.JTextField();
        txtostate = new javax.swing.JTextField();
        txtocity = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtoaddress = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userproject/icon/male_user_50px.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 0, 60, 60));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("|");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 0, 40, 60));

        jLabel3.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Welcome to easy buy");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 250, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userproject/icon/icons8_menu_48px_1.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 60));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setText("|");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 30, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userproject/icon/search_26px.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 40, 60));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setText("|");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, -1, 60));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userproject/icon/group_message_26px.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, 40, 60));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userproject/icon/bell_26px.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 0, 40, 60));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Hello, User");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 20, 120, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1930, 70));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userproject/icon/home_24px.png"))); // NOI18N
        jButton3.setText("   HOME");
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 270, 80));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userproject/icon/shopping_cart_24px.png"))); // NOI18N
        jButton2.setText("  ORDERS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 270, 80));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userproject/icon/template_26px.png"))); // NOI18N
        jButton4.setText("  PRODUCTS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 270, 80));

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userproject/icon/shopping_cart_24px.png"))); // NOI18N
        jButton5.setText("  CARD TO EDIT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 270, 80));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 270, 960));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbloco.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbloco.setForeground(new java.awt.Color(0, 153, 153));
        lbloco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userproject/icon/edit_property_24px.png"))); // NOI18N
        lbloco.setText(" Fill Your Order Details ");
        jPanel4.add(lbloco, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 510, 60));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Enter Your Pin Code*");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 260, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Enter Your Name*");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 170, 50));

        txtopincode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtopincode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtopincodeActionPerformed(evt);
            }
        });
        jPanel4.add(txtopincode, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 330, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Enter Your Mobile No*");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 260, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Enter Your State*");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 260, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Enter Your City*");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 260, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Enter Your Address*");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 260, 30));

        op.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        op.setText("Online Payment");
        op.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opActionPerformed(evt);
            }
        });
        jPanel4.add(op, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, 140, -1));

        cod.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cod.setText("cash on delivery");
        cod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codActionPerformed(evt);
            }
        });
        jPanel4.add(cod, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, 140, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Payment Mode*");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 120, -1));

        tbnpay.setBackground(new java.awt.Color(204, 204, 255));
        tbnpay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tbnpay.setForeground(new java.awt.Color(51, 51, 51));
        tbnpay.setText("Make Payment");
        tbnpay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnpayActionPerformed(evt);
            }
        });
        jPanel4.add(tbnpay, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, 340, 40));

        txtoname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(txtoname, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 330, 30));

        txtomobile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(txtomobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 330, 30));

        txtostate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(txtostate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 330, 30));

        txtocity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(txtocity, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 330, 30));

        txtoaddress.setColumns(20);
        txtoaddress.setRows(5);
        jScrollPane1.setViewportView(txtoaddress);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 330, 70));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 590, 640));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 1660, 950));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        /*cart to edit button*/

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tbnpayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnpayActionPerformed

        
/*make payment btn*/
int total = 0;
            try{
         String url = "jdbc:mysql://localhost:3306/project";
                    String uname = "root";
                    String passs = "";

                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = DriverManager.getConnection(url, uname, passs);

                    Statement stt = con.createStatement();
                    
                    ResultSet st = stt.executeQuery("SELECT pprice,bqty FROM ctoe");
                    
                    
                //ResultSet st = statement.executeQuery("SELECT pprice,bqty FROM ctoe");
            int pq;
            
            int q;
            while (st.next()) {
                pq = st.getInt(1);
                q = st.getInt(2);
                total = total + pq * q;
                q = 0;
                pq = 0;
            }
               
        
    }catch(Exception a){
        System.out.println(a);
        
    }
   
   
   try{
       String oname=txtoname.getText();
   String omobile=txtomobile.getText();
   String ostate=txtostate.getText();
   String ocity=txtocity.getText();
   String oaddress=txtoaddress.getText();
   String opincode=txtopincode.getText();

                    String url = "jdbc:mysql://localhost:3306/project";
                    String uname = "root";
                    String upass = "";


                    Class.forName("com.mysql.jdbc.Driver");
                    Connection connection = DriverManager.getConnection(url, uname, upass);

                    Statement statement = connection.createStatement();


                    String qqq = "insert into ordd(name,mobileno,state,city,address,pincode,totalpayment) values(?,?,?,?,?,?,?)";

                    PreparedStatement pst = connection.prepareStatement(qqq);
                    
                    String s=String.valueOf(total);
                    pst.setString(1, oname);
                    pst.setString(2, omobile);
                    pst.setString(3, ostate);
                    pst.setString(4, ocity);
                    pst.setString(5, oaddress);
                    pst.setString(6,opincode );
                    pst.setString(7,s );
                    
                    if (oname.isEmpty() || omobile.isEmpty() || ostate.isEmpty() || ocity.isEmpty() || oaddress.isEmpty()||opincode.isEmpty()) {
                        JOptionPane.showMessageDialog(null,"Fill all Text");
                    } else {
                        pst.executeUpdate();
                         JOptionPane.showMessageDialog(null,"Done od");
                        
                        
                    }    
}catch(Exception a){
    System.out.println(a);
}





        // TODO add your handling code here:
    }//GEN-LAST:event_tbnpayActionPerformed

    private void opActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opActionPerformed

    private void codActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codActionPerformed

    private void txtopincodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtopincodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtopincodeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        confodr cod = new confodr();
        cod.setVisible(true);



        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(confolist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(confolist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(confolist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(confolist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new confolist().setVisible(true);
            }
        });
    }

    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton cod;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbloco;
    private javax.swing.JRadioButton op;
    private javax.swing.JButton tbnpay;
    private javax.swing.JTextArea txtoaddress;
    private javax.swing.JTextField txtocity;
    private javax.swing.JTextField txtomobile;
    private javax.swing.JTextField txtoname;
    private javax.swing.JTextField txtopincode;
    private javax.swing.JTextField txtostate;
    // End of variables declaration//GEN-END:variables
}
